CREATE TABLE `USER` (
  `ID` CHAR(36) PRIMARY KEY,
  `PUBLIC_ID` INTEGER UNIQUE,
  `NAME` VARCHAR(25),
  `LAST_NAME` VARCHAR(200),
  `NICKNAME` VARCHAR(16) UNIQUE,
  `E_MAIL` VARCHAR(500) UNIQUE,
  `PASSWORD` VARCHAR(500),
  `ROLE` VARCHAR(50),
  `CREATED_AT` DATE
);

ALTER TABLE `USER` MODIFY PUBLIC_ID INT AUTO_INCREMENT;
ALTER TABLE `USER` AUTO_INCREMENT=1000;

CREATE TABLE `USER_RECOVERY` (
  `USER_ID` CHAR(36) PRIMARY KEY,
  `RECOVERY_KEY` VARCHAR(500) UNIQUE,
  `CHANGE_PASSWORD_CODE` CHAR(6),
  `CHANGE_PASSWORD_CODE_EXPIRATION` DATE
);

CREATE TABLE `FILE_HISTORY` (
  `ID` CHAR(36) PRIMARY KEY,
  `USER_ID` CHAR(36),
  `FILE_NAME` VARCHAR(100),
  `FILE_EXTENSION` VARCHAR(5),
  `CONTENT_TYPE` VARCHAR(15),
  `FILE_PATH` VARCHAR(300),
  `CREATED_AT` DATE
);

ALTER TABLE `USER_RECOVERY` ADD FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);
ALTER TABLE `FILE_HISTORY` ADD FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);
